/**
  ******************************************************************************
  * @file    ui.h
  * @brief   Rotary-encoder + push-button PID tuner with VOFA+ FireWater output
  *
  *  Hardware
  *  --------
  *  TIM3  encoder mode   Knob A/B → adjust the selected PID parameter
  *  PB7   push-button    Cycle Kp → Ki → Kd (active-low, internal PULLUP)
  *
  *  Output (UART1 DMA-TX, FireWater protocol for VOFA+)
  *  ----
 *  Every TIM8 tick : 5-channel FireWater float frame (24 bytes)
 *     [angle | kp | ki | kd | param_idx] [0x00 0x00 0x80 0x7F]
 *     VOFA+ chart: ch1=angle, ch2=Kp, ch3=Ki, ch4=Kd, ch5=selected(0/1/2)
  *
 *  UART baud rate : 460800, 24-byte frame → max ~1920 frames/s.
 *                   TIM8 runs at 10625 Hz; DMA tx_busy flag throttles
 *                   naturally to the UART bandwidth limit.
 *
 *  Integration
 *  -----------
 *  1. Call UI_Init()  after SPWM_Start()
 *  2. Call UI_Poll()  from the main loop
 *  3. In HAL_TIM_PeriodElapsedCallback : if TIM8 → UI_TIM8Callback()
 *  4. In HAL_UART_TxCpltCallback       : if USART1 → UI_TxCpltCallback()
 *  Note: TIM8_UP_IRQHandler and NVIC (priority 10) generated by CubeMX.
  ******************************************************************************
  */
#ifndef UI_H
#define UI_H

#include "spwm.h"

/* ---- Adjustment step per encoder detent --------------------------------- */
#define UI_STEP_KP          0.001f
#define UI_STEP_KI          0.0001f
#define UI_STEP_KD          0.0001f

/* ---- FireWater text frame buffer (ASCII CSV + '\n', 64 bytes max) ------- */
#define UI_FW_BUF_SIZE      64u

/* ---- Button software debounce (milliseconds via HAL_GetTick) ------------ */
#define UI_BTN_DEBOUNCE_MS  50u

/* ---- Parameter index ----------------------------------------------------- */
typedef enum
{
    UI_PARAM_KP    = 0,
    UI_PARAM_KI    = 1,
    UI_PARAM_KD    = 2,
    UI_PARAM_COUNT = 3
} UI_ParamIndex;

/* ---- Handle -------------------------------------------------------------- */
typedef struct
{
    SPWM_HandleTypeDef  *hspwm;         /* SPWM controller (owns PID)       */
    UART_HandleTypeDef  *huart;         /* USART1, DMA-TX configured        */
    TIM_HandleTypeDef   *htim_enc;      /* TIM3 encoder handle              */

    int16_t              enc_last;      /* last TIM3 CNT read (signed 16)   */
    uint8_t              param_idx;     /* currently selected param (0-2)   */

    volatile uint8_t     tx_busy;       /* UART DMA TX in progress          */

    uint8_t              fw_buf[UI_FW_BUF_SIZE];  /* FireWater text frame  */

    uint32_t             btn_time;      /* HAL_GetTick() at last edge       */
    uint8_t              btn_state;     /* debounced pin state (1 = idle)   */
} UI_HandleTypeDef;

/* ---- API ----------------------------------------------------------------- */

/**
 * @brief Initialise UI, start TIM3 encoder and TIM8 base interrupt.
 *        Call AFTER SPWM_Start().
 */
void UI_Init(UI_HandleTypeDef  *hui,
             SPWM_HandleTypeDef *hspwm,
             UART_HandleTypeDef *huart,
             TIM_HandleTypeDef  *htim_enc,
             TIM_HandleTypeDef  *htim_tick);

/**
 * @brief Poll encoder delta and button state.  Non-blocking, call from main loop.
 */
void UI_Poll(UI_HandleTypeDef *hui);

/**
 * @brief Must be called from HAL_TIM_PeriodElapsedCallback when htim == TIM8.
 *        Streams angle float and (every 500 ms) PID text via UART DMA.
 */
void UI_TIM8Callback(UI_HandleTypeDef *hui);

/**
 * @brief Must be called from HAL_UART_TxCpltCallback to release the DMA lock.
 */
void UI_TxCpltCallback(UI_HandleTypeDef *hui);

#endif /* UI_H */
